<?php

use App\Couriers\Providers\BlueExGateway;
use App\Couriers\Providers\CallCourierGateway;
use App\Couriers\Providers\FedExGateway;
use App\Couriers\Providers\LeopardsGateway;
use App\Couriers\Providers\MnpGateway;
use App\Couriers\Providers\SandboxCourierGateway;
use App\Couriers\Providers\TcsGateway;

return [
    'default_mode' => env('COURIER_MODE', 'sandbox'),

    'providers' => [
        'TCS' => [
            'name' => 'TCS',
            'gateway' => TcsGateway::class,
            'production_adapter' => true,
            'mode' => env('TCS_MODE', env('COURIER_MODE', 'sandbox')),
            'base_url' => env('TCS_API_BASE_URL'),
            'account_number' => env('TCS_ACCOUNT_NUMBER'),
            'username' => env('TCS_API_USERNAME'),
            'password' => env('TCS_API_PASSWORD'),
            'book_endpoint' => env('TCS_BOOK_ENDPOINT', '/book'),
            'track_endpoint' => env('TCS_TRACK_ENDPOINT', '/track'),
            'cancel_endpoint' => env('TCS_CANCEL_ENDPOINT', '/cancel'),
            'return_proof_endpoint' => env('TCS_RETURN_PROOF_ENDPOINT', '/return-proof'),
            'webhook_secret' => env('TCS_WEBHOOK_SECRET'),
            'required_credentials' => ['base_url', 'account_number', 'username', 'password'],
            'endpoint_keys' => ['book_endpoint', 'track_endpoint', 'cancel_endpoint', 'return_proof_endpoint'],
            'standard_fields' => ['reference', 'receiver_name', 'receiver_phone', 'receiver_address', 'city', 'weight_grams', 'cod_amount', 'description'],
            'webhook_events' => ['picked', 'transit', 'out_for_delivery', 'delivered', 'returned', 'cancelled'],
        ],
        'FDX' => [
            'name' => 'FedEx',
            'gateway' => FedExGateway::class,
            'production_adapter' => false,
            'mode' => env('FEDEX_MODE', env('COURIER_MODE', 'sandbox')),
            'base_url' => env('FEDEX_API_BASE_URL'),
            'account_number' => env('FEDEX_ACCOUNT_NUMBER'),
            'client_id' => env('FEDEX_CLIENT_ID'),
            'client_secret' => env('FEDEX_CLIENT_SECRET'),
            'oauth_endpoint' => env('FEDEX_OAUTH_ENDPOINT', '/oauth/token'),
            'ship_endpoint' => env('FEDEX_SHIP_ENDPOINT', '/ship/v1/shipments'),
            'track_endpoint' => env('FEDEX_TRACK_ENDPOINT', '/track/v1/trackingnumbers'),
            'cancel_endpoint' => env('FEDEX_CANCEL_ENDPOINT', '/ship/v1/shipments/cancel'),
            'webhook_secret' => env('FEDEX_WEBHOOK_SECRET'),
            'required_credentials' => ['base_url', 'account_number', 'client_id', 'client_secret'],
            'endpoint_keys' => ['oauth_endpoint', 'ship_endpoint', 'track_endpoint', 'cancel_endpoint'],
            'standard_fields' => ['shipper', 'recipient', 'service_type', 'packages', 'customs_value', 'tracking_number'],
            'webhook_events' => ['shipment.created', 'tracking.updated', 'delivery.completed', 'return.exception'],
        ],
        'LCS' => [
            'name' => 'Leopards',
            'gateway' => LeopardsGateway::class,
            'production_adapter' => false,
            'mode' => env('LEOPARDS_MODE', env('COURIER_MODE', 'sandbox')),
            'base_url' => env('LEOPARDS_API_BASE_URL'),
            'api_key' => env('LEOPARDS_API_KEY'),
            'api_password' => env('LEOPARDS_API_PASSWORD'),
            'book_endpoint' => env('LEOPARDS_BOOK_ENDPOINT', '/bookPacket/format/json/'),
            'track_endpoint' => env('LEOPARDS_TRACK_ENDPOINT', '/trackBookedPacket/format/json/'),
            'cancel_endpoint' => env('LEOPARDS_CANCEL_ENDPOINT', '/cancelBookedPacket/format/json/'),
            'webhook_secret' => env('LEOPARDS_WEBHOOK_SECRET'),
            'required_credentials' => ['base_url', 'api_key', 'api_password'],
            'endpoint_keys' => ['book_endpoint', 'track_endpoint', 'cancel_endpoint'],
            'standard_fields' => ['consignee_name', 'consignee_phone', 'address', 'destination_city', 'pieces', 'weight', 'cod_amount'],
            'webhook_events' => ['booked', 'in_transit', 'delivered', 'returned'],
        ],
        'TRX' => [
            'name' => 'Trax',
            'gateway' => SandboxCourierGateway::class,
            'production_adapter' => false,
            'mode' => env('TRAX_MODE', env('COURIER_MODE', 'sandbox')),
            'base_url' => env('TRAX_API_BASE_URL'),
            'api_key' => env('TRAX_API_KEY'),
            'book_endpoint' => env('TRAX_BOOK_ENDPOINT', '/shipments'),
            'track_endpoint' => env('TRAX_TRACK_ENDPOINT', '/shipments/track'),
            'cancel_endpoint' => env('TRAX_CANCEL_ENDPOINT', '/shipments/cancel'),
            'webhook_secret' => env('TRAX_WEBHOOK_SECRET'),
            'required_credentials' => ['base_url', 'api_key'],
            'endpoint_keys' => ['book_endpoint', 'track_endpoint', 'cancel_endpoint'],
            'standard_fields' => ['order_id', 'customer_name', 'customer_phone', 'address', 'city', 'amount', 'weight'],
            'webhook_events' => ['pickup', 'in_transit', 'delivered', 'returned'],
        ],
        'MNP' => [
            'name' => 'M&P',
            'gateway' => MnpGateway::class,
            'production_adapter' => false,
            'mode' => env('MNP_MODE', env('COURIER_MODE', 'sandbox')),
            'base_url' => env('MNP_API_BASE_URL'),
            'username' => env('MNP_API_USERNAME'),
            'password' => env('MNP_API_PASSWORD'),
            'book_endpoint' => env('MNP_BOOK_ENDPOINT', '/book'),
            'track_endpoint' => env('MNP_TRACK_ENDPOINT', '/track'),
            'cancel_endpoint' => env('MNP_CANCEL_ENDPOINT', '/cancel'),
            'webhook_secret' => env('MNP_WEBHOOK_SECRET'),
            'required_credentials' => ['base_url', 'username', 'password'],
            'endpoint_keys' => ['book_endpoint', 'track_endpoint', 'cancel_endpoint'],
            'standard_fields' => ['shipper_ref', 'consignee', 'destination', 'weight', 'cod', 'remarks'],
            'webhook_events' => ['manifested', 'in_transit', 'delivered', 'returned'],
        ],
        'BEX' => [
            'name' => 'BlueEx',
            'gateway' => BlueExGateway::class,
            'production_adapter' => false,
            'mode' => env('BLUEEX_MODE', env('COURIER_MODE', 'sandbox')),
            'base_url' => env('BLUEEX_API_BASE_URL'),
            'username' => env('BLUEEX_API_USERNAME'),
            'password' => env('BLUEEX_API_PASSWORD'),
            'book_endpoint' => env('BLUEEX_BOOK_ENDPOINT', '/booking'),
            'track_endpoint' => env('BLUEEX_TRACK_ENDPOINT', '/tracking'),
            'cancel_endpoint' => env('BLUEEX_CANCEL_ENDPOINT', '/cancel'),
            'webhook_secret' => env('BLUEEX_WEBHOOK_SECRET'),
            'required_credentials' => ['base_url', 'username', 'password'],
            'endpoint_keys' => ['book_endpoint', 'track_endpoint', 'cancel_endpoint'],
            'standard_fields' => ['order_ref', 'name', 'phone', 'address', 'city', 'weight', 'cod_amount'],
            'webhook_events' => ['booked', 'picked', 'delivered', 'returned'],
        ],
        'OVR' => [
            'name' => 'Overland',
            'gateway' => SandboxCourierGateway::class,
            'production_adapter' => false,
            'mode' => env('OVERLAND_MODE', env('COURIER_MODE', 'sandbox')),
            'base_url' => env('OVERLAND_API_BASE_URL'),
            'api_key' => env('OVERLAND_API_KEY'),
            'book_endpoint' => env('OVERLAND_BOOK_ENDPOINT', '/book'),
            'track_endpoint' => env('OVERLAND_TRACK_ENDPOINT', '/track'),
            'cancel_endpoint' => env('OVERLAND_CANCEL_ENDPOINT', '/cancel'),
            'webhook_secret' => env('OVERLAND_WEBHOOK_SECRET'),
            'required_credentials' => ['base_url', 'api_key'],
            'endpoint_keys' => ['book_endpoint', 'track_endpoint', 'cancel_endpoint'],
            'standard_fields' => ['reference', 'receiver', 'phone', 'address', 'city', 'weight_kg', 'cod_amount'],
            'webhook_events' => ['booked', 'loaded', 'delivered', 'returned'],
        ],
        'CC' => [
            'name' => 'Call Courier',
            'gateway' => CallCourierGateway::class,
            'production_adapter' => false,
            'mode' => env('CALL_COURIER_MODE', env('COURIER_MODE', 'sandbox')),
            'base_url' => env('CALL_COURIER_API_BASE_URL'),
            'login_id' => env('CALL_COURIER_LOGIN_ID'),
            'key' => env('CALL_COURIER_KEY'),
            'book_endpoint' => env('CALL_COURIER_BOOK_ENDPOINT', '/booking'),
            'track_endpoint' => env('CALL_COURIER_TRACK_ENDPOINT', '/tracking'),
            'cancel_endpoint' => env('CALL_COURIER_CANCEL_ENDPOINT', '/cancel'),
            'webhook_secret' => env('CALL_COURIER_WEBHOOK_SECRET'),
            'required_credentials' => ['base_url', 'login_id', 'key'],
            'endpoint_keys' => ['book_endpoint', 'track_endpoint', 'cancel_endpoint'],
            'standard_fields' => ['login_id', 'shipper_ref', 'consignee_name', 'mobile', 'address', 'destination', 'cod'],
            'webhook_events' => ['picked', 'in_process', 'delivered', 'returned'],
        ],
    ],
];
